### ISSUE TITLE
issue with library mod on 1.11.2

### ISSUE THREAD

**Issue by warcommando2** [TeamMD5/NineTailLib#2] opened 2017-06-05 20:22 UTC
hi there;

this is the start up log on the issue i am having. I am redoing my modpack called HermletteCraft Chronicles on curse/twitch.
https://pastebin.com/WC4FCGLN
https://pastebin.com/sStnmngV

As soon as it launch's it crash's with your mods enabled, this is the only log i have with it is the start up log. When i launch it through the curse or any other launcher i get that report. When i do have the library file off it loads the tails mod fine but no proper GUI screen because the library file is not present.

hit play on custom profile
opened the options in the minecraft launcher used below augment saved and hit play
startup/crashlog on pastebin

-CryoTech/warcommando2

**Comment by KitsuneAlex** [comment] 2017-06-06 13:15
thanks for pointing that out! i already found out what the problem is, im a derp X3 will be fixed in the next build. :3 i have one question tho: why are you using my lib even tho there's currently no mods for it? :D

**Comment by KitsuneAlex** [comment] 2017-06-27 15:42
Should be fixed in the latest build

**Closed by KitsuneAlex** 2017-06-27 15:42 UTC
